name: Deploy Backend

on:
  push:
    branches: [ "main" ]
    paths:
      - "backend/**"
      - ".github/workflows/deploy-backend.yml"

jobs:
  deploy:
    runs-on: self-hosted   # 이것만 있으면 됨

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build backend image
        run: |
          docker build -t backend-repo:latest -f backend/Dockerfile ./backend
          docker tag backend-repo:latest 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/backend-repo:latest
          docker push 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/backend-repo:latest

      - name: Restart backend container
        run: |
          docker rm -f backend || true
          docker pull 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/backend-repo:latest
          docker run -d --name backend -p 8080:8080 --restart unless-stopped \
            314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/backend-repo:latest
