name: Deploy Frontend

on:
  push:
    branches: [ "main" ]
    paths:
      - "frontend/**"
      - ".github/workflows/deploy-frontend.yml"

jobs:
  deploy:
    runs-on: self-hosted   # 이것만 있으면됨

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region ap-northeast-2 \
          | docker login --username AWS --password-stdin 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com

      - name: Build frontend image
        run: |
          docker build -t frontend-repo:latest -f frontend/Dockerfile ./frontend
          docker tag frontend-repo:latest 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-repo:latest
          docker push 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-repo:latest

      - name: Restart frontend container
        run: |
          docker rm -f frontend || true
          docker pull 314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-repo:latest
          docker run -d --name frontend -p 80:80 --restart unless-stopped \
            314432538223.dkr.ecr.ap-northeast-2.amazonaws.com/frontend-repo:latest
